inputs:
  jira-hostname:
    required: true
  jira-username:
    required: true
  jira-password:
    required: true
  tickets:
    required: false
  version-result:
    required: true
runs:
  using: 'node16'
  main: 'index.js'