inputs: 
  jira-hostname:
    required: true
  jira-username:
    required: true
  jira-password:
    required: true
  from-revision:
    required: false
    default: HEAD~1
runs:
  using: 'node16'
  main: 'index.js'