inputs:
  jira-hostname:
    required: true
  jira-username:
    required: true
  jira-password:
    required: true 
  ticket-id:
    required: true
  action-id: 
    required: true
runs:
  using: 'node16'
  main: 'index.js'